httpClient:
  timeout: 500ms
  connectionTimeout: 500ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 2500ms
  retries: 0

server:
  requestLog:
    appenders:
      - type: console
        threshold: $env:CONSOLE_LOG_LEVEL:WARN

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: $env:DEFAULT_LOG_LEVEL:INFO
  # Logger-specific levels.
  loggers:
    org.skife.jdbi.v2: $env:JDBI_LOG_LEVEL:DEBUG
    nl.info: $env:NL_INFO_LOG_LEVEL:DEBUG

  appenders:
    - type: console
      threshold: $env:CONSOLE_LOG_LEVEL:DEBUG
